### ISSUE TITLE
Strange behaviour when using waitForEmptyQueue

### ISSUE THREAD

**Issue by massimocode** [Lewerow/zurvan#39]
Hi

I have created a repo here with some tests that are acting strange:
https://github.com/massimocode/zurvan-issue

It seems like calling zurvan.waitForEmptyQueue twice does more than calling it once! For me, that indicates that the queue was not fully empty when the promise resolved.

Can you take a look please?

**Comment by massimocode** [comment]
I have been looking into it more and it seems like it's an issue when using the request-promise node module. See the specs for more info/scenarios.

**Comment by Lewerow** [comment]
it's possible that this is related to usage of Q - as a Promise library it may cache `setImmediate` instance from the original, nodejs version

I'll investigate it

**Comment by Lewerow** [comment]
Ok, some early findings - `request-promise` uses `bluebird` under the hood. Since `bluebird` caches original instance of `setImmediate`, one provided by `zurvan` is not used at all. You could probably solve this by `bluebird: require('bluebird')` parameter to `interceptTimers`, albeit I agree that adding explicit dependency just for same of TCs in not nice and makes code more rigid.
To properly solve this, #26 would need to be implemented

I'm not sure how is it with Q, but as far as I checked on Node.js 0.10+ they use the global `setImmediate`, so it shouldn't be a problem.

**Comment by massimocode** [comment]
Hi Tomasz

I have tried this but it doesn't seem to fully resolve the issue.

I need to do wait for empty queue 3 times (i.e. zurvan.waitForEmptyQueue().then(zurvan.waitForEmptyQueue).then(zurvan.waitForEmptyQueue)) without passing bluebird into interceptTimers, and if I pass bluebird in then I still need to do waitForEmptyQueue twice... one time does not solve it.

Is there anything I can do to help you resolve this?

**Comment by Lewerow** [comment]
Can you push the version where you pass `bluebird` to `zurvan.interceptTimers`? I believe #26 should solve the problem, but it won't be ready until next week for sure, so I'd prefer to make sure that the problem is `bluebird` scheduler and not some other internal `zurvan`, `Q` or `bluebird` stuff

**Comment by massimocode** [comment]
ok so I've been working on this for some time now and I think there's something else going on. The reason is that I do this in my test set up:
```
require('request-promise/node_modules/bluebird').setScheduler(fn => global.setImmediate(fn))
```
And the problem still occurs... and if I add a console log to my scheduler function it does log out, but well after waitForEmptyQueue has resolved.

I will try to get you an isolated example of this.

**Comment by massimocode** [comment]
Here you go:
https://github.com/massimocode/zurvan-issue

**Comment by Lewerow** [comment]
Ok, apparently you're right - adding `bluebird` is necessary, but not sufficient.

It seems that scheduler somehow manages to get unnoticed after sentries - we have double-end-of-queue guard to deal with this problem, but apparently it's not sufficient. I'm going to treat this as priority, since that's pretty ugly bug. I'll keep you posted,

**Comment by Lewerow** [comment]
I think a follow-up may be needed here.
I am able to solve your specific case by scheduling queue verification one end-of-event-loop event later, but I'm still looking for a more robust solution that would be able to handle all special cases. No luck yet though.

**Comment by Lewerow** [comment]
Apparently I wasn't able to find out a 100%-reliable solution. I believe the current workaround should solve your problem (at least your TC passed).

Sorry it took so long, please let me know if it works for you

**Comment by massimocode** [comment]
I tested this and it seems to work fine for now. I will let you know if I have any issues
